on: [push, pull_request]

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install

      - name: run linter
        id: eslint
        run: npm run lint

      - if: ${{ failure() }}
        name: Comment on PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Lint failed with the following errors:
            ${{ steps.eslint.outputs.stdout }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  stylelint:
    name: Stylelint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install

      - name: run linter
        run: npm run lint:styles