on: pull_request

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install

      - name: run linter
        id: eslint
        run: |
          VAR=$((npm run lint) 2>&1)
          echo "::set-output name=LINT_RESULT::$VAR"

      - if: ${{ failure() }}
        name: Comment on PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Lint failed with the following errors:
            ${{ steps.eslint.outputs.LINT_RESULT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Echo message
        run: echo ${{ steps.eslint.outputs.LINT_RESULT }}

  # stylelint:
  #   name: Stylelint
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Setup Node.js
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: 16
  #     - name: Install dependencies
  #       run: npm install

  #     - name: run linter
  #       run: npm run lint:styles