on: pull_request

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: |
          echo "::set-output name=lint-test::$(npm run lint)\n"
        id: eslint

      - name: Test echo
        run: echo ${{ steps.eslint.outputs.lint-test }}

      # - if: ${{ failure() }}
      #   name: Comment on PR
      #   uses: thollander/actions-comment-pull-request@v1
      #   with:
      #     message: |
      #       Lint failed            
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # stylelint:
  #   name: Stylelint
  #   runs-on: ubuntu-latest
    
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Setup Node.js
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: 16
  #     - name: Install dependencies
  #       run: npm install

  #     - name: Run stylelint
  #       run: npm run lint:styles

  #     - if: ${{ failure() }}
  #       name: Comment on PR
  #       uses: thollander/actions-comment-pull-request@v1
  #       with:
  #         message: |
  #           Stylelint failed          
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
