on: push

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: lts/*
      - run: npm install
      - run: npm run lint
      - run: npm run lint:styles